server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Local system logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: francoise-bootstrap
          __path__: /var/log/*.log

  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          host: francoise-bootstrap
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - labels:
          stream:
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # Terraform logs (when available)
  - job_name: terraform
    static_configs:
      - targets:
          - localhost
        labels:
          job: terraform
          host: francoise-bootstrap
          __path__: /var/log/terraform/*.log

  # Ansible logs (when available)
  - job_name: ansible
    static_configs:
      - targets:
          - localhost
        labels:
          job: ansible
          host: francoise-bootstrap
          __path__: /var/log/ansible/*.log