global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Françoise Bootstrap (self-monitoring)
  - job_name: 'francoise-bootstrap'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'francoise-bootstrap'
          role: 'ops-console'

  # Production VMs
  - job_name: 'app-k3s'
    static_configs:
      - targets: ['10.98.0.11:9100']
        labels:
          instance: 'app-k3s'
          role: 'kubernetes'

  - job_name: 'db-postgres'
    static_configs:
      - targets: ['10.98.0.10:9100']
        labels:
          instance: 'db-postgres'
          role: 'database'

  - job_name: 'etoile-pbs'
    static_configs:
      - targets: ['10.98.0.12:9100']
        labels:
          instance: 'etoile-pbs'
          role: 'backup'

  # Proxmox Host
  - job_name: 'neve-proxmox'
    static_configs:
      - targets: ['10.98.0.1:9100']
        labels:
          instance: 'neve'
          role: 'hypervisor'

  # Self-monitoring of observability stack
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']

  - job_name: 'loki'
    static_configs:
      - targets: ['localhost:3100']

  # Terraform/Ansible monitoring (via file_sd if configured)
  - job_name: 'infrastructure-jobs'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/*.json'
        refresh_interval: 30s