name: CI

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-site
  cancel-in-progress: true

jobs:
  build:
    name: Build (site/)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: site/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint (if available)
        run: |
          if npm run -s | grep -q "^ *lint *"; then
            npm run lint
          else
            echo "No lint script, skipping."
          fi

      - name: Build
        run: npm run build

      - name: Run Lighthouse CI performance audit
        continue-on-error: true
        run: npx lhci autorun --staticDistDir=dist
