name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: site/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          if npm run -s lint >/dev/null 2>&1; then npm run lint; else echo "No lint script"; fi

      - name: Type & Integrations Check
        run: |
          npx astro check || true

      - name: Build
        run: npm run build
