name: "🚀 Trigger Aggressive Auto-Fix"

permissions:
  contents: write
  actions: write
  pull-requests: write
  issues: write

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/trigger-aggressive-fix.yml"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "🚀 Trigger Aggressive Security Auto-Fix"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'security-autofix-aggressive.yml',
              ref: 'main',
              inputs: {
                fix_level: 'high'
              }
            });
            console.log('🎯 Aggressive security auto-fix triggered with HIGH level!');
